name: Lint and Compile

on:
  release:
    types:
      - created
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11
      - run: pip install .[dev]
      - run: python -m ruff --format=github .
  build:
    runs-on: ubuntu-22.04
    needs:
      - lint
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11
      - uses: justalemon/VersionPatcher@v0.7
        with:
          version: 0.0.1-alpha.${{ github.run_number }}
          pyproject-files: "pyproject.toml"
      - run: pip install .[dev]
      - run: python -m build
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ github.event.repository.name }}
          path: dist/*
